### ISSUE TITLE
Must rename extensions for use in workes to js (.cjs does not work)

### ISSUE THREAD

**Issue by LaurentDhont** [juanelas/paillier-bigint#11] opened 2021-05-20 16:05 UTC
TypeError [ERR_WORKER_UNSUPPORTED_EXTENSION]: The worker script extension must be ".js" or ".mjs". Received ".cjs"

Just rename the files and it will work.

**Comment by RaulBejarano** [comment] 2021-07-29 10:57
Hello, I'm getting the same error and I don't know how to solve it.

**Comment by juanelas** [comment] 2021-08-04 11:28
Are you using node version 10? Updating to a more recent version (node 10 is no longer supported) should fix the issue. If that is not the case, I would need more details about how to reproduce the issue.

**Comment by juanelas** [comment] 2022-01-17 10:17
Since I cannot reproduce the issue, I (temporarily) close it.

**Closed as completed by juanelas** 2022-01-17 10:17 UTC
